name: Publish release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  draft:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Cargo publish
      run: |
        echo ${{ secrets.CARGO_LOGIN }} | cargo login
        manifests=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | awk '{if ($0 ~ /.*Cargo.toml/) print $0}' | sort -r)
        for manifest in "$manifests"; do
          module=$(cargo read-manifest --manifest-path "$manifest" | jq -r .name)
          if [[ "$module" == "utoipa" ]]; then
            cargo publish
          else
            cargo publish -p "$module"
          fi
        done
